name: CI
on: push

jobs:
    check-style:
        name: Check code style
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run check-style

    backend-auth-build:
        name: Build authentication backend
        needs: check-style
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend_auth

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run lint:ci
            - run: npm run build
            - uses: actions/upload-artifact@main
              with:
                  name: backend-auth-build
                  path: backend_auth/build

    backend-auth-test:
        name: Test authentication backend
        needs: backend-auth-build
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend_auth

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run test:ci

    backend-food-build:
        name: Build food backend
        needs: check-style
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend_food

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run lint:ci
            - run: npm run build
            - uses: actions/upload-artifact@main
              with:
                  name: backend-food-build
                  path: backend_food/build

    backend-food-test:
        name: Test food backend
        needs: backend-food-build
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend_food

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run test:ci

    backend-stats-build:
        name: Build statistics backend
        needs: check-style
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend_statistics

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run lint:ci
            - run: npm run build
            - uses: actions/upload-artifact@main
              with:
                  name: backend-stats-build
                  path: backend_statistics/build

    backend-stats-test:
        name: Test statistics backend
        needs: backend-stats-build
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: backend_statistics

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                  node-version: 16
                  cache: npm
            - run: npm ci
            - run: npm run test:ci
